services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_DB: hw3
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  app:
    build: .
    container_name: python_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:Qwerty123@postgres:5432/hw3
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
